In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import numpy as np

In [2]:
train_datagen = ImageDataGenerator(
        rotation_range=360,
        width_shift_range=0.0,
        height_shift_range=0.0,
        rescale=1./255,
        shear_range=0.0,
        zoom_range=0.0,
        fill_mode="nearest")

train_generator = train_datagen.flow_from_directory("data/train",
                                                target_size = (300, 300),
                                                batch_size = 16,
                                                class_mode = 'categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory("data/test",
                                                 target_size=(300, 300),
                                                 batch_size=16,
                                                 class_mode='categorical')

Found 331 images belonging to 4 classes.
Found 83 images belonging to 4 classes.


In [3]:
model = Sequential()

model.add(Conv2D(16, (3, 3), input_shape = (300, 300, 3), activation = 'relu', padding = 'same'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(32, (3, 3), activation = 'relu', padding = 'same'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(32, (3, 3), activation = 'relu', padding = 'same'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(64, (3, 3), activation = 'relu', padding = 'same'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Flatten())
model.add(Dense(units = 64, activation = 'relu'))
model.add(Dropout(rate=0.3))
model.add(Dense(units = 4, activation = 'softmax'))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 300, 300, 16)      448       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 150, 150, 16)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 150, 150, 32)      4640      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 75, 75, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 75, 75, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 37, 37, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 37, 37, 64)        1

In [5]:
model.fit(train_generator,
                    steps_per_epoch=331//16,
                    validation_data=test_generator,
                    validation_steps=83//16,
                    epochs = 5)

Epoch 1/5
20/20 [==============================] - 15s 740ms/step - loss: 1.3126 - accuracy: 0.4000 - val_loss: 1.1600 - val_accuracy: 0.4750
Epoch 2/5
20/20 [==============================] - 18s 924ms/step - loss: 1.0306 - accuracy: 0.5683 - val_loss: 0.8501 - val_accuracy: 0.5250
Epoch 3/5
20/20 [==============================] - 22s 1s/step - loss: 0.8976 - accuracy: 0.5492 - val_loss: 0.7697 - val_accuracy: 0.6500
Epoch 4/5
20/20 [==============================] - 25s 1s/step - loss: 0.9508 - accuracy: 0.5397 - val_loss: 0.8223 - val_accuracy: 0.5750
Epoch 5/5
20/20 [==============================] - 21s 1s/step - loss: 0.8484 - accuracy: 0.5524 - val_loss: 0.7810 - val_accuracy: 0.6000


In [6]:
scores = model.evaluate(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

5/5 [==============================] - 1s 196ms/step - loss: 0.7703 - accuracy: 0.5875
accuracy: 58.75%


In [9]:
model.save('model/my_model.h5')

In [10]:
output = model.predict(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

{'100won': 0, '10won': 1, '500won': 2, '50won': 3}
[[0.002 0.992 0.002 0.005]
 [0.361 0.059 0.429 0.151]
 [0.000 0.997 0.000 0.002]
 [0.000 1.000 0.000 0.000]
 [0.369 0.041 0.437 0.153]
 [0.387 0.029 0.420 0.163]
 [0.412 0.015 0.442 0.131]
 [0.000 0.998 0.000 0.001]
 [0.383 0.027 0.452 0.138]
 [0.371 0.043 0.423 0.163]
 [0.000 0.999 0.000 0.000]
 [0.385 0.032 0.431 0.152]
 [0.150 0.443 0.174 0.233]
 [0.279 0.147 0.334 0.240]
 [0.401 0.020 0.443 0.137]
 [0.350 0.065 0.393 0.192]
 [0.000 0.999 0.000 0.001]
 [0.404 0.018 0.442 0.136]
 [0.343 0.070 0.401 0.186]
 [0.290 0.121 0.361 0.228]
 [0.187 0.387 0.209 0.217]
 [0.399 0.021 0.446 0.135]
 [0.386 0.030 0.435 0.149]
 [0.359 0.051 0.409 0.181]
 [0.385 0.031 0.437 0.147]
 [0.000 0.998 0.000 0.001]
 [0.363 0.046 0.422 0.169]
 [0.379 0.033 0.452 0.136]
 [0.000 1.000 0.000 0.000]
 [0.359 0.060 0.424 0.158]
 [0.189 0.330 0.222 0.260]
 [0.001 0.997 0.000 0.002]
 [0.390 0.026 0.448 0.136]
 [0.407 0.019 0.444 0.131]
 [0.405 0.017 0.444 0.134]
 [0.